### ISSUE TITLE
似乎是因为notify而崩端

### ISSUE THREAD

**Issue by Dreamtell** [dyyibang/NullPoint-Client#1]
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-08-05 20:15:18
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050)
	at me.nullpoint.mod.modules.impl.client.Notify.onRender2D(Notify.java:34)
	at me.nullpoint.api.managers.ModuleManager.lambda$render2D$12(ModuleManager.java:267)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at me.nullpoint.api.managers.ModuleManager.render2D(ModuleManager.java:267)
	at net.minecraft.class_329.handler$ccj000$nullpoint$onRender(class_329.java:6984)
	at net.minecraft.class_329.method_1753(class_329.java:382)
	at net.minecraft.class_757.method_3192(class_757.java:912)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050)
	at me.nullpoint.mod.modules.impl.client.Notify.onRender2D(Notify.java:34)
	at me.nullpoint.api.managers.ModuleManager.lambda$render2D$12(ModuleManager.java:267)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at me.nullpoint.api.managers.ModuleManager.render2D(ModuleManager.java:267)
	at net.minecraft.class_329.handler$ccj000$nullpoint$onRender(class_329.java:6984)
	at net.minecraft.class_329.method_1753(class_329.java:382)

-- Uptime --
Details:
	JVM uptime: 154.010s
	Wall uptime: 143.298s
	High-res time: 135.614s
	Client ticks: 2459 ticks / 122.950s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Affected level --
Details:
	All players: 7 total; [class_746['Dreamtell'/1113845, l='ClientLevel', x=-13.02, y=8.00, z=-54.02], class_745['犬夜叉瑟提'/1093372, l='ClientLevel', x=-15.89, y=4.00, z=-61.07], class_745['_Night_Mare_God_'/1111216, l='ClientLevel', x=-1.48, y=122.00, z=-5.66], class_745['大爱仙尊'/1056904, l='ClientLevel', x=-14.36, y=4.00, z=-58.02], class_745['孤独的合适'/1111816, l='ClientLevel', x=3.36, y=121.00, z=-4.37], class_745['有种别打我qwq'/1078965, l='ClientLevel', x=-9.77, y=121.00, z=-7.79], class_745['icharao'/1100048, l='ClientLevel', x=9.04, y=121.00, z=1.13]]
	Chunk stats: 1024, 109
	Level dimension: minecraft:the_end
	Level spawn location: World: (0,121,0), Section: (at 0,9,0 in 0,7,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 755 game time, 755 day time
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:0dd7b98:1723) <- Purpur
	Server type: Non-integrated multiplayer server
	Tracked entity count: 12

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, appleskin, betterf3, bettertaskbar, betterthirdperson, borderlessmining, caffeineconfig, capes, chat_heads, chatshot, chunksfadein, cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, damagevignette, dark-loading-screen, detailab, double_hotbar, draggable_lists, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, glsl, glsl-common, halohud, ias, immediatelyfast, immersive-tooltip, ingameime, inventoryhud, inventoryprofilesnext, iris, kaleido, lazydfu, leahs-immersive-thunder, libipn, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, nullpoint, playeranimator, satin, seriousplayeranimations, smoothscroll, sodium, sodium-extra, starlight, tia, viafabricplus, waveycapes, xaerominimap, xaeroworldmap, yaclx, yet_another_config_lib_v3, file/Minecraft-Mod-Language-Modpack-Converted-1.20.4.zip, file/高版本ESPADA PACK.zip, file/【best】 cpvp pack.zip, file/§gEspadaPack§a1.20.1+NEW, file/[new]EspadaPack, file/guiretextures-1.10.zip, file/无阉割梅梅pack.zip, high_contrast, file/Ph1lzas_Netherite.zip, file/背景_12)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 22.0.2, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 625079200 bytes (596 MiB) / 1577058304 bytes (1504 MiB) up to 8053063680 bytes (7680 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12490F
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 4060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2788
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6070
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 29017.84
	Virtual memory used (MB): 16145.88
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 385.02
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1152m -Xmx7680m
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20.3
		architectury: Architectury 11.1.17
		betterf3: BetterF3 9.0.2
		bettertaskbar: Better Taskbar 1.8.0
		betterthirdperson: Better Third Person 1.9.0
		borderlessmining: Borderless Mining 1.1.9+1.20.2
		capes: Capes 1.5.3+1.20.2
		chat_heads: Chat Heads 0.12.3
		chatshot: ChatShot 1.0.1
		chunksfadein: Chunks Fade In 1.0.0-1.20.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		damagevignette: DamageVignette 3.0.0
		dark-loading-screen: Dark Loading Screen 1.6.14
		detailab: Detail Armor Bar 2.6.3+1.20.4-fabric
		double_hotbar: Double Hotbar 1.3.2.1-mc1.20.2-fabric
		draggable_lists: Draggable Lists 1.0.5
		fabric-api: Fabric API 0.97.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.63+6605d1a84f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.6+d331d3144f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 6.0.3
		forgeconfigapiport: Forge Config API Port 20.4.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		glsl-common: GLSL Panorama 0.2.6
			glsl: GLSL Panorama 0.2.6
		halohud: Halo HUD 4.2+1.20.2
			yaclx: YetAnotherConfigLibExtensions 1.10+1.20
		i18nupdatemod: I18nUpdateMod 3.5.5
		ias: In-Game Account Switcher 9.0.0
		iceberg: Iceberg 1.1.18
		immediatelyfast: ImmediatelyFast 1.2.18+1.20.4
			net_lenni0451_reflect: Reflect 1.3.4
		immersive-tooltip: Immersive:Tooltip 1.20.3-1.2.0
		ingameime: ContingameIME 1.0.7-1.20.1
		inventoryhud: Inventory HUD + 3.4.22
		inventoryprofilesnext: Inventory Profiles Next 1.10.10
		iris: Iris 1.7.1+mc1.20.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemborders: Item Borders 1.2.1
		java: OpenJDK 64-Bit Server VM 22
		kaleido: Kaleido 1.20.1-1.1.3
		lazydfu: LazyDFU 0.1.3
		leahs-immersive-thunder: Immersive Thunder 1.20.4+1.2.2
		libipn: libIPN 4.0.2
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.4
		mousetweaks: Mouse Tweaks 2.26
		nullpoint: nullpoint v2.1.3
		placeholder-api: Placeholder API 2.4.0-pre.1+1.20.4
		playeranimator: Player Animator 1.0.2-rc1+1.20.4
		prism: Prism 1.0.6
		satin: Satin 1.16.0
		seriousplayeranimations: Serious Player Animations 1.1.1
		smoothscroll: Smooth Scroll 2.1.2
		sodium: Sodium 0.5.8+mc1.20.4
		sodium-extra: Sodium Extra 0.5.4+mc1.20.4-build.116
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		tia: Tiny Item Animations 1.20-1.1
		viafabricplus: ViaFabricPlus 3.1.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 4.10.0
			com_viaversion_viaversion-common: viaversion-common 4.10.0
			de_florianmichael_classic4j: Classic4J 2.0.2
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.5
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.5
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.5
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.4.1
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_raphimc_minecraftauth: MinecraftAuth 4.0.0
			net_raphimc_viaaprilfools: ViaAprilFools 2.0.11
			net_raphimc_viabedrock: ViaBedrock 0.0.6-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 2.2.22
			net_raphimc_vialoader: ViaLoader 2.2.13
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			org_yaml_snakeyaml: snakeyaml 2.2
		waveycapes: WaveyCapes 1.4.7
		xaerominimap: Xaero's Minimap 24.2.0
		xaeroworldmap: Xaero's World Map 1.38.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.4-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: ComplementaryReimagined_r5.1.1 + EuphoriaPatches_1.1
		Profile: Custom (+108 options changed by user)
	Launched Version: Dreamtell's Minecraft For 2b2t with Nullpoint
	Launcher name: PCL
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.70, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Operation is not valid from a preview context.' x 6376
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 5/8 chunks
	Resource Packs: vanilla, fabric, file/Minecraft-Mod-Language-Modpack-Converted-1.20.4.zip, file/高版本ESPADA PACK.zip, file/【best】 cpvp pack.zip, file/§gEspadaPack§a1.20.1+NEW, file/[new]EspadaPack, file/guiretextures-1.10.zip, file/无阉割梅梅pack.zip, high_contrast, file/Ph1lzas_Netherite.zip, file/背景_12)
	Current Language: zh_cn
	Locale: zh_CN
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-12490F

**Comment by Cai-kunkun** [comment]
哥给个nullpoint的jar

**Comment by Cai-kunkun** [comment]
Resolved?Buy Shader Client
